
export const GET_CATAGORY = 'GET_CATAGORY'
export const LODING_CATAGORY = 'LODING_CATAGORY'
export const ERROR_CATAGORY = 'ERROR_CATAGORY' 
export const ADD_CATAGORY = 'ADD_CATAGORY' 
export const DELETE_CATAGORY = 'DELETE_CATAGORY' 
export const EDIT_CATAGORY = 'EDIT_CATAGORY' 

