
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const GET_MEDICINE = 'GET_MEDICINE'
export const LODING_MEDICINE = 'LODING_MEDICINE'
export const ERROR_MEDICINE = 'ERROR_MEDICINE' 
export const ADD_MEDICINE = 'ADD_MEDICINE' 
export const DELETE_MEDICINE = 'DELETE_MEDICINE' 
export const EDIT_MEDICINE = 'EDIT_MEDICINE' 

export const GET_PATIENT = "GET_PATIENT"
export const LODING_PATIENT = "LODING_PATIENT"
export const ERROR_PATIENT = "ERROR_PATIENT"
export const ADD_PATIENT = 'ADD_PATIENT' 
export const DELETE_PATIENT = 'DELETE_PATIENT' 
export const EDIT_PATIENT = 'EDIT_PATIENT' 